name: Stubbed Push versioned images for Piccadilly Connect to Digital Ocean Repository

on: workflow_dispatch

jobs:
  push-test-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: TannerLankford1223/actions-test-service

      - name: Get version from file
        run: cat VERSION || echo '0.0.0'
    

            

            
        