name: Stubbed Push versioned images for Piccadilly Connect to Digital Ocean Repository

on: workflow_dispatch

jobs:
  push-test-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: TannerLankford1223/actions-test-service
          token: ${{ secrets.GH_PAT }}

      - name: Get version from file
        run: cat VERSION || echo '0.0.0'
      
      - name: Set SERVICE_NAME from repository
        run: echo "SERVICE_NAME=${{ env.SERVICE_NAME }}" >> $GITHUB_ENV

      - name: Print SERVICE_NAME
        run: echo "SERVICE_NAME is ${{ env.SERVICE_NAME }}"

  push-another-test-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: TannerLankford1223/another-actions-test
          token: ${{ secrets.GH_PAT }}

      - name: Get version from file
        run: cat VERSION || echo '0.0.0'
      
      - name: Set SERVICE_NAME from repository
        run: echo "SERVICE_NAME=${{ env.SERVICE_NAME }}" >> $GITHUB_ENV

      - name: Print SERVICE_NAME
        run: echo "SERVICE_NAME is ${{ env.SERVICE_NAME }}"
    

            

            
        