name: Tag new npm package and create release

on:
  push:
    branches:
      - main
    paths:
        - package.json

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Tag on NPM Package Version Change
        uses: neverendingqs/gh-action-tag-on-npm-version@master

      - name: Use the Tag Variable in Another Step
        run: echo "The created tag is ${{ env.TAG }}"

