name: Tag new npm package and create release

on:
  push:
    branches:
      - main
    paths:
        - package.json

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Tag on NPM Package Version Change
        id: tag_version
        uses: neverendingqs/gh-action-tag-on-npm-version@master

      - name: Set Tag Output
        id: latest-tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Use the Tag Variable in Another Step
        run: echo "The created tag is ${{ steps.latest-tag.outputs.tag }}"

      - name: Create Release
        uses: "actions/github-script@v6"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: false,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: ${{ steps.latest-tag.outputs.tag }},
              });

            } catch (error) {
              core.setFailed(error.message);
            }
