name: Tag new npm package and create release

on:
  push:
    branches:
      - main
    paths:
        - package.json

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Tag on NPM Package Version Change
        id: tag_version
        uses: neverendingqs/gh-action-tag-on-npm-version@master

      - name: Set Tag Output
        id: set_tag_output
        run: echo "::set-output name=tag::${{ steps.tag_version.outputs.TAG }}"

      - name: Use the Tag Variable in Another Step
        run: echo "The created tag is ${{ steps.set_tag_output.outputs.tag }}"
